### ISSUE TITLE
Plugin Crashing at startup 

### ISSUE THREAD

**Issue by legolasdimir** [Garulf/TenorGIF#16]
Here is the exception that shows after I try to start it manually and use it. 

```python
Flow Launcher version: 1.16.2
OS Version: 22631.3007
IntPtr Length: 8
x64: True

Python Path: C:\Users\bryan.pruett\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 01/25/2024 08:24:08
Exception:
TenorGIF Exception: 
Websites: https://github.com/Garulf/TenorGIF
Author: Garulf
Version: 2.2.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\bryan.pruett\AppData\Roaming\FlowLauncher\Plugins\TenorGIF-v2.2.0-ea63a322-4908-48e0-b530-efca975421a5\run.py", line 9, in <module>
    from plugin.tenor_flow import TenorFlow
  File "C:\Users\bryan.pruett\AppData\Roaming\FlowLauncher\Plugins\TenorGIF-v2.2.0-ea63a322-4908-48e0-b530-efca975421a5\plugin\tenor_flow.py", line 5, in <module>
    from flox import Flox
  File "C:\Users\bryan.pruett\AppData\Roaming\FlowLauncher\Plugins\TenorGIF-v2.2.0-ea63a322-4908-48e0-b530-efca975421a5\lib\flox\__init__.py", line 47, in <module>
    raise FileNotFoundError(LAUNCHER_NOT_FOUND_MSG)
FileNotFoundError: Unable to locate Launcher directory
Current working directory: C:\Windows\system32

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\bryan.pruett\AppData\Roaming\FlowLauncher\Plugins\TenorGIF-v2.2.0-ea63a322-4908-48e0-b530-efca975421a5\run.py", line 9, in <module>
    from plugin.tenor_flow import TenorFlow
  File "C:\Users\bryan.pruett\AppData\Roaming\FlowLauncher\Plugins\TenorGIF-v2.2.0-ea63a322-4908-48e0-b530-efca975421a5\plugin\tenor_flow.py", line 5, in <module>
    from flox import Flox
  File "C:\Users\bryan.pruett\AppData\Roaming\FlowLauncher\Plugins\TenorGIF-v2.2.0-ea63a322-4908-48e0-b530-efca975421a5\lib\flox\__init__.py", line 47, in <module>
    raise FileNotFoundError(LAUNCHER_NOT_FOUND_MSG)
FileNotFoundError: Unable to locate Launcher directory
Current working directory: C:\Windows\system32

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
```
Here is the log file

[2024-01-25.txt](https://github.com/Garulf/TenorGIF/files/14054047/2024-01-25.txt)

**Comment by Garulf** [comment]
This error is a bug with Flow Launcher. When you try and activate a plugin that's not fully loaded due to an error loading it's settings.
